/**
 * Base Agent Class
 * Fort Homes QMS - AI Agent Framework
 */

import fs from 'fs';
import path from 'path';
import { prisma } from '../database';

export interface AgentConfig {
  name: string;
  description: string;
  temperature?: number;
  maxTokens?: number;
}

export interface GenerationContext {
  companyInfo?: any;
  phases?: any;
  holdPoints?: any;
  itps?: any;
  [key: string]: any;
}

export abstract class BaseAgent {
  protected config: AgentConfig;
  protected context: GenerationContext;

  constructor(config: AgentConfig) {
    this.config = config;
    this.context = {};
    this.loadContext();
  }

  /**
   * Load company data from JSON files
   */
  protected loadContext(): void {
    const dataDir = path.join(process.cwd(), 'data');
    
    try {
      this.context.companyInfo = JSON.parse(
        fs.readFileSync(path.join(dataDir, 'company-info.json'), 'utf-8')
      );
    } catch (error) {
      console.warn('Warning: Could not load company-info.json');
    }

    try {
      this.context.phases = JSON.parse(
        fs.readFileSync(path.join(dataDir, 'phases.json'), 'utf-8')
      );
    } catch (error) {
      console.warn('Warning: Could not load phases.json');
    }

    try {
      this.context.holdPoints = JSON.parse(
        fs.readFileSync(path.join(dataDir, 'hold-points.json'), 'utf-8')
      );
    } catch (error) {
      console.warn('Warning: Could not load hold-points.json');
    }

    try {
      this.context.itps = JSON.parse(
        fs.readFileSync(path.join(dataDir, 'itps.json'), 'utf-8')
      );
    } catch (error) {
      console.warn('Warning: Could not load itps.json');
    }
  }

  /**
   * Get agent name
   */
  public getName(): string {
    return this.config.name;
  }

  /**
   * Get agent description
   */
  public getDescription(): string {
    return this.config.description;
  }

  /**
   * Abstract method to be implemented by subclasses
   */
  abstract execute(...args: any[]): Promise<any>;

  /**
   * Create audit trail entry
   */
  protected async createAuditTrail(
    documentId: string,
    action: string,
    changes: any,
    userId: string = 'system',
    username: string = 'AI Agent'
  ): Promise<void> {
    try {
      await prisma.auditTrail.create({
        data: {
          documentId,
          action,
          userId,
          username,
          changes: JSON.stringify(changes),
          comment: `Generated by ${this.config.name}`,
        },
      });
    } catch (error) {
      console.error('Error creating audit trail:', error);
    }
  }

  /**
   * Read template file
   */
  protected readTemplate(templateType: string, templateName: string): string {
    const templatePath = path.join(
      process.cwd(),
      'src',
      'templates',
      templateType,
      `${templateName}.md`
    );
    
    try {
      return fs.readFileSync(templatePath, 'utf-8');
    } catch (error) {
      console.error(`Error reading template: ${templatePath}`);
      throw error;
    }
  }

  /**
   * Load markdown document from docs/
   */
  protected loadDocument(docPath: string): string {
    const fullPath = path.join(process.cwd(), 'docs', docPath);
    try {
      return fs.readFileSync(fullPath, 'utf-8');
    } catch (error) {
      console.error(`Error loading document: ${fullPath}`);
      throw error;
    }
  }
}

export default BaseAgent;
